### ISSUE TITLE
Example project ?

### ISSUE THREAD

**Issue by joeblew99** [slicebit/qb#55]
I really like the approach this takes. A new project I have starting next week would be a good candidate for this.

I have 2 requests:

Is there an example project ? This helps because it acts as s test harness and gets me and others quick way to get going

What's not done yet, but considered needed. This helps me and others know what we will hit if we start using this in a project. It also allows others to decide before they hit the roadblocks, but also to implement the needed feature

**Comment by aacanakin** [comment]
I can provide a simple user authentication and session system using qb from the command line. It can use [cobra](https://github.com/spf13/cobra) to create, login, logout users. Would that be helpful for you?

Currently, I can think of a migration engine and relationship support as missing features. I haven't come up with a great design of relationship support yet. I don't think that feature to be crucial for qb because foreign key constraints are supported.

Moreover, the only concurrency check is when you create a new transaction. If you are using qb with concurrency techniques, things may crash. The concurrency tests are also missing in qb currently.

Lastly, I plan to change the table api where you can create tables without using structs like [this](https://github.com/aodin/sol#sol). I expect not to change the session api but things may change in 0.2 release.

**Comment by joeblew99** [comment]
That example sounds good to me.

Thanks

**Comment by cdevienne** [comment]
If the example is a complete (yet simple) web application with authentication, then I suggest to make it a different project, as it involves a lot choices of other libraries, hence gives a very opinionated use case of qb. And I think qb should, for a while, focus on the schema definition and query builder, not too much on things that will depend on it.

**Comment by aacanakin** [comment]
I'll provide examples after 0.3 release where changes wouldn't be that much big like 0.2 or 0.1 (hopefully). It'll be in a separate repo.
